sonar.organization=prasiddhpatel
sonar.projectKey=lms-backend-flask   # Make sure this matches the project key in SonarCloud
sonar.sources=.
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
